name: Build Wine for FreeBSD
on:
  workflow_dispatch:
    inputs:
      winetype:
        description: "The type of Wine to build"
        required: true
        default: "staging"
        type: choice
        options:
        - staging
        - proton
        - devel
        - patched
      wineversion:
        description: "The version of Wine to build"
        required: true
        default: "7.4"
        type: string
run-name: Build wine-${{ inputs.winetype }} ${{ inputs.wineversion }} for FreeBSD 14.3

jobs:
  freebsd64:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    steps:
    - uses: actions/checkout@v4
    - name: Build Wine for FreeBSD 64-bit
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          sed -i '' -e 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
          pkg install -y git nim ca_root_nss
        run: |
          git clone https://github.com/freebsd/freebsd-ports.git /usr/ports
          /usr/local/nim/bin/nim --hints:off build.nims ${{ inputs.wineversion }} ${{ inputs.winetype }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: '14.3-amd64'
        tag_name: '14.3-amd64'
        files: '*.pkg'

  freebsd32:
    needs: freebsd64
    runs-on: ubuntu-latest
    timeout-minutes: 80
    steps:
    - uses: actions/checkout@v4
    - name: Build Wine for FreeBSD 32-bit
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        run: |
          sh ./32bit.sh ${{ inputs.wineversion }} ${{ inputs.winetype }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: '14.3-i386'
        tag_name: '14.3-i386'
        files: '*.pkg'
