name: Build Wine for FreeBSD

on:
  workflow_dispatch:
    inputs:
      winetype:
        description: "The type of Wine to build"
        required: true
        default: "staging"
        type: choice
        options:
        - staging
        - proton
        - devel
        - patched
      wineversion:
        description: "The version of Wine to build"
        required: true
        default: "7.4"
        type: string

jobs:
  freebsd64:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build Wine for FreeBSD 64-bit
      uses: cross-platform-actions/action@v0.13.0
      with:
        shell: sh
        operating_system: freebsd
        architecture: x86-64
        version: '13.2'
        run: |
          sudo sed -i '' -e 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
          sudo pkg install -y git nim
          sudo git clone https://github.com/freebsd/freebsd-ports.git /usr/ports
          sudo nim --hints:off build.nims ${{ inputs.wineversion }} ${{ inputs.winetype }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: '13.2-amd64'
        tag_name: '13.2-amd64'
        files: '*.pkg'

  freebsd32:
    continue-on-error: true
    needs: freebsd64
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build Wine for FreeBSD 32-bit
      uses: cross-platform-actions/action@v0.13.0
      with:
        shell: sh
        operating_system: freebsd
        architecture: x86-64
        version: '13.2'
        run: |
          sudo sh ./32bit.sh ${{ inputs.wineversion }} ${{ inputs.winetype }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: '13.2-i386'
        tag_name: '13.2-i386'
        files: '*.pkg'
