name: Build All Wine for FreeBSD

on: workflow_dispatch

jobs:
  freebsd64:
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        winetype: [devel, staging, patched]
        wineversion: [7.21, 7.4, 7.17]
        exclude:
          - winetype: patched
            wineversion: 7.17
        include:
          - winetype: proton
            wineversion: 6.3-2
          - winetype: proton
            wineversion: 7.0-6
          - winetype: proton
            wineversion: 7.0-10
          - winetype: proton
            wineversion: 7.0-20
          - winetype: proton
            wineversion: 7.0-25
          - winetype: proton
            wineversion: 7.0-29
          - winetype: proton
            wineversion: 7.0-32
          - winetype: proton
            wineversion: 7.0-36
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build Wine for FreeBSD 64-bit
      uses: cross-platform-actions/action@v0.13.0
      with:
        memory: 6G
        shell: sh
        operating_system: freebsd
        architecture: x86-64
        version: '13.2'
        run: |
          sudo sed -i '' -e 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
          sudo pkg install -y git nim
          sudo git clone https://github.com/freebsd/freebsd-ports.git /usr/ports
          sudo nim --hints:off build.nims ${{ matrix.wineversion }} ${{ matrix.winetype }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: 13.2-amd64
        tag_name: 13.2-amd64
        files: '*.pkg'

  freebsd32:
    needs: freebsd64
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        winetype: [devel, staging, patched]
        wineversion: [7.21, 7.4, 7.17]
        exclude:
          - winetype: patched
            wineversion: 7.17
        include:
          - winetype: proton
            wineversion: 6.3-2
          - winetype: proton
            wineversion: 7.0-6
          - winetype: proton
            wineversion: 7.0-10
          - winetype: proton
            wineversion: 7.0-20
          - winetype: proton
            wineversion: 7.0-25
          - winetype: proton
            wineversion: 7.0-29
          - winetype: proton
            wineversion: 7.0-32
          - winetype: proton
            wineversion: 7.0-36
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build Wine for FreeBSD 32-bit
      uses: cross-platform-actions/action@v0.13.0
      with:
        memory: 6G
        shell: sh
        operating_system: freebsd
        architecture: x86-64
        version: '13.2'
        run: |
          sudo sh ./32bit.sh ${{ matrix.wineversion }} ${{ matrix.winetype }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: 13.2-i386
        tag_name: 13.2-i386
        files: '*.pkg'
